### ISSUE TITLE
 Implement OpenAI Content Moderation 

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/ckeditor5-ai-agent#14]
## Why are we doing this work

We are implementing content moderation to ensure that user inputs are screened for inappropriate or harmful content before being sent to the GPT model. This adds an important safety layer to our application, helping to prevent misuse and maintain a safe environment for all users. It also helps protect the owner of the API account from their account being closed due to violating terms of service etc.

## Relevant links

- [OpenAI Moderation API Documentation](https://platform.openai.com/docs/guides/moderation)

## Requirements

- Implement a moderation check before sending user input to the GPT model
- Use OpenAI's moderation API
- Ensure performance impact is minimal
- Using a moderation check is optional, it is only active when enabled in plugin config

## Implementation plan

- [ ] Create a new `moderateContent` function in `SlashCommandPlugin`
  ```javascript
  async function moderateContent(input) {
    const response = await fetch('https://api.openai.com/v1/moderations', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ input })
    });
    return response.json();
  }
  ```

- [ ] Modify `handleSlashCommand` to include moderation check
  ```javascript
  async handleSlashCommand(prompt, parent, cancel) {
    try {
      const moderationResult = await this.moderateContent(prompt);
      if (moderationResult.results[0].flagged) {
        this.showGptErrorToolTipAtBottom("Cannot process your query, please adjust your query");
        return;
      }
      // Proceed with existing GPT request logic
    } catch (error) {
      console.error('Moderation error:', error);
      this.showGptErrorToolTipAtBottom("Error in content moderation");
    }
  }
  ```

- [ ] Implement error handling for moderation API failures
- [ ] Update UI feedback to include moderation status
  - [ ] Update existing loader to show after moderation passes

## Extra information

![image](https://github.com/user-attachments/assets/7a1e8148-7543-422d-8297-065948d9aa75)
