### ISSUE TITLE
Implement content fetching from links / URLs in SlashCommandPlugin using r.jina.ai

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/ckeditor5-ai-agent#15]
## Why are we doing this work

We want to enhance the SlashCommandPlugin to allow users to fetch content from URLs directly within the editor. This will improve the user experience by enabling them to gather information from external sources without leaving the editor, streamlining the research and content creation process.

## Example prompts:

> The rise of cloud computing has revolutionized the way businesses operate. From small startups to large enterprises, organizations are increasingly adopting cloud-based solutions. However, the benefits and drawbacks of cloud computing are still debated in many circles.
> 
> **/Compile benefits of cloud computing:
> https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-cloud-computing/,
> https://aws.amazon.com/what-is-cloud-computing/**
> 
> Estimated contextSize split (assuming 4000 total tokens for contextSize):
> - Editor content: 300 tokens (7.5%)
> - Fetched content: 3700 tokens (92.5%) [Rebalanced from 70% due to shorter editor content]
>   - Azure URL: 300 tokens (100% of corpus included, 300 / 300 total corpus length)
>   - AWS URL: 3400 tokens (85% of corpus included, 3400 / 4000 total corpus length)

> Artificial Intelligence (AI) has become a buzzword in recent years, with applications ranging from voice assistants to autonomous vehicles. However, the full scope of AI's potential impact on society is still being explored. Some argue that AI will lead to unprecedented advancements in various fields, while others warn of potential risks and ethical concerns.
> 
> The development of AI technologies has accelerated rapidly, driven by advances in machine learning, neural networks, and big data analytics. Industries such as healthcare, finance, and manufacturing are already seeing significant transformations due to AI integration. For instance, AI-powered diagnostic tools are enhancing medical imaging analysis, while algorithmic trading systems are reshaping financial markets.
> 
> Despite these advancements, concerns persist about the ethical implications of AI. Issues such as data privacy, algorithmic bias, and the potential for job displacement are at the forefront of public discourse. As AI systems become more sophisticated, questions about accountability and transparency in AI decision-making processes grow increasingly important.
> 
> **/Summarize the 'Applications' section of AI:
> https://en.wikipedia.org/wiki/Artificial_intelligence#Applications**
> 
> Estimated contextSize split (assuming 4000 total tokens for contextSize):
> - Editor content: 1200 tokens (30%)
> - Fetched content: 2800 tokens (70%)
>   - Wikipedia URL: 2800 tokens (70% of corpus included, 2800 / 4000 total corpus length)

> The telecommunications industry is constantly evolving, with new technologies promising faster speeds and improved connectivity. Two of the most talked-about advancements in recent years are 5G and Wi-Fi 6. Both technologies aim to enhance our digital experiences, but they approach this goal in different ways. 5G focuses on cellular networks, promising ultra-fast speeds and low latency for mobile devices, while Wi-Fi 6 aims to improve wireless networking in homes and businesses. Understanding the strengths and limitations of each technology is crucial for consumers and businesses alike.
> 
> **/Compare 5G and Wi-Fi 6 technologies:
> https://www.qualcomm.com/5g/what-is-5g,
> https://www.wi-fi.org/discover-wi-fi/wi-fi-certified-6**
> 
> Estimated contextSize split (assuming 4000 total tokens for contextSize):
> - Editor content: 600 tokens (15%)
> - Fetched content: 3400 tokens (85%) [Rebalanced from 70% due to shorter editor content]
>   - Qualcomm URL: 1700 tokens (50% of corpus included, 1700 / 3400 total fetched content)
>   - Wi-Fi Alliance URL: 1700 tokens (50% of corpus included, 1700 / 3400 total fetched content)

> The smartphone market is highly competitive, with new models being released regularly. Android phones, in particular, offer a wide range of options catering to different price points and user preferences. When considering the best Android phones, factors such as camera quality, battery life, processing power, and software features play crucial roles.
> 
> **/Using these sources write an SEO optimized blog post "top 10 best Android phones 2024", only include android phones in the post:
> https://www.techradar.com/news/best-phone
> https://www.zdnet.com/article/best-phone/
> https://www.tomsguide.com/best-picks/best-phones
> https://www.cnet.com/tech/mobile/best-phone/
> https://www.gsmarena.com/best_smartphones_buyers_guide-review-2030p1.php**
> 
> Estimated contextSize split (assuming 4000 total tokens for contextSize):
> - Editor content: 400 tokens (10%)
> - Fetched content: 3600 tokens (90%) [Rebalanced from 70% due to shorter editor content]
>   - TechRadar URL: 720 tokens (20% of corpus included, 720 / 3600 total fetched content)
>   - ZDNET URL: 720 tokens (20% of corpus included, 720 / 3600 total fetched content)
>   - Tom's Guide URL: 720 tokens (20% of corpus included, 720 / 3600 total fetched content)
>   - CNET URL: 720 tokens (20% of corpus included, 720 / 3600 total fetched content)
>   - GSMArena URL: 720 tokens (20% of corpus included, 720 / 3600 total fetched content)

> The concept of sustainable development has gained significant traction in recent years, as the world grapples with the challenges of climate change, resource depletion, and social inequality. Sustainable development aims to meet the needs of the present without compromising the ability of future generations to meet their own needs. This approach integrates economic, social, and environmental considerations to create a more balanced and resilient future.
>
> However, implementing sustainable development practices on a global scale presents numerous challenges. These include balancing economic growth with environmental protection, addressing social inequalities, and fostering international cooperation on issues such as climate change mitigation and adaptation.
>
> **/Analyze the progress and challenges in achieving the UN Sustainable Development Goals (SDGs):
> https://sdgs.un.org/goals,
> https://www.un.org/sustainabledevelopment/progress-report/,
> https://www.nature.com/articles/d41586-020-02373-7**
>
> Estimated contextSize split (assuming 4000 total tokens for contextSize):
> - Editor content: 800 tokens (20%)
> - Fetched content: 3200 tokens (80%) [Rebalanced from 70% due to complex topic]
> - UN SDGs URL: 1067 tokens (33.33% of corpus included, 1067 / 3200 total fetched content)
> - UN Progress Report URL: 1067 tokens (33.33% of corpus included, 1067 / 3200 total fetched content)
> - Nature Article URL: 1066 tokens (33.33% of corpus included, 1066 / 3200 total fetched content)

> The field of quantum computing has been making significant strides in recent years, promising to revolutionize various sectors including cryptography, drug discovery, and financial modeling. Unlike classical computers that use bits to process information, quantum computers leverage quantum bits or qubits, which can exist in multiple states simultaneously due to the principle of superposition.
>
> This unique property allows quantum computers to perform certain calculations exponentially faster than classical computers. However, the technology is still in its early stages, facing challenges such as maintaining qubit coherence and scaling up to practical levels.
>
> Despite these hurdles, major tech companies and research institutions are investing heavily in quantum computing research and development. The potential applications of this technology are vast, ranging from optimizing supply chains to simulating complex molecular structures for new materials and drugs.
>
> **/Explain the current state of quantum computing technology and its potential applications:
> https://www.ibm.com/quantum/what-is-quantum-computing,
> https://www.nature.com/articles/d41586-019-02602-8,
> https://www.nist.gov/blogs/taking-measure/quantum-computing-progress-and-prospects,
> https://www.scientificamerican.com/article/quantum-computing-has-arrived/**
>
> Estimated contextSize split (assuming 4000 total tokens for contextSize):
> - Editor content: 1000 tokens (25%)
> - Fetched content: 3000 tokens (75%)
> - IBM URL: 750 tokens (25% of corpus included, 750 / 3000 total fetched content)
> - Nature Article URL: 750 tokens (25% of corpus included, 750 / 3000 total fetched content)
> - NIST Blog URL: 750 tokens (25% of corpus included, 750 / 3000 total fetched content)
> - Scientific American URL: 750 tokens (25% of corpus included, 750 / 3000 total fetched content)

## Relevant links

- [Jina AI Reader Documentation](https://github.com/jina-ai/reader)
- [r.jina.ai API](https://r.jina.ai/)

## Requirements

- Implement a `/fetch` command that accepts a URL as an argument
- Use the r.jina.ai hosted solution to fetch content from the provided URL
- Handle errors gracefully and provide user feedback, including for invalid URLs and blocked URL requests
- Support fetching content from specific sections of a page using URL hash fragments (already supported by r.Jina API)
- Allow fetching from multiple URLs in a single command
- Develop a system to intelligently parse and format fetched content for seamless integration into the prompt
- Create clear demarcations between different contexts (editor content, fetched content from various sources) within the prompt
- Modify the prompt generation to incorporate fetched contexts effectively
- Create an adaptive contextSize management system that targets a 30:70 ratio between editor and fetched content, with built-in redistribution logic to ensure efficient use of available tokens within the total contextSize boundary

### Testing the requirements with the above examples:

1. Cloud Computing Example:
Pass: 
- The response includes benefits from both Azure and AWS sources, with more content from AWS due to its larger token allocation.
- The response acknowledges the debate mentioned in the editor content but focuses on benefits as requested.
- Clear distinction between information from editor content and fetched sources.

Fail: 
- The response only includes benefits from Azure or heavily favors Azure despite its smaller token allocation.
- No indication that the editor content's context about debates in cloud computing was considered.
- Mixing of editor content and fetched content without clear demarcation.

2. AI Applications Example:
Pass: 
- The summary focuses specifically on the 'Applications' section of AI from Wikipedia, covering key points proportional to the 70% of fetched content.
- The response acknowledges the broader AI context provided in the editor content but doesn't elaborate on it.
- Clear separation between the general AI discussion in editor content and specific applications from Wikipedia.

Fail: 
- The summary includes information not related to AI applications or draws heavily from the editor content instead of the Wikipedia source.
- Inability to distinguish between the broader AI context in editor content and the specific 'Applications' section requested from Wikipedia.

3. 5G and Wi-Fi 6 Comparison Example:
Pass: 
- The comparison includes balanced information from both Qualcomm (5G) and Wi-Fi Alliance (Wi-Fi 6) sources, reflecting the equal token distribution.
- The response acknowledges the importance of understanding strengths and limitations as mentioned in the editor content.
- Clear distinction between the general context provided in editor content and specific details from fetched sources.

Fail: 
- The comparison heavily favors one technology over the other or includes information not present in the fetched sources.
- No indication that the editor content's context about the importance of understanding both technologies was considered.
- Mixing of editor content and fetched content without clear demarcation.

4. Top 10 Android Phones 2024 Example:
Pass: 
- The blog post includes information from all five sources, focuses only on Android phones, and is SEO optimized.
- The response considers the factors mentioned in the editor content (camera quality, battery life, etc.) when discussing the phones.
- Clear distinction between the general context provided in editor content and specific phone details from fetched sources.

Fail: 
- The post includes non-Android phones, heavily favors one source over others, or lacks SEO optimization.
- No indication that the factors mentioned in the editor content were considered in the phone evaluations.
- Inability to distinguish between editor content and information from fetched sources.

5. UN Sustainable Development Goals Example:
Pass: 
- The analysis includes information from all three sources, with roughly equal representation, covering both progress and challenges in achieving the SDGs.
- The response acknowledges the broader context of sustainable development provided in the editor content.
- Clear separation between the general sustainable development discussion in editor content and specific SDG progress/challenges from fetched sources.

Fail: 
- The analysis is heavily skewed towards one source or fails to address both progress and challenges.
- No indication that the broader context of sustainable development from the editor content was considered.
- Mixing of editor content and fetched content without clear demarcation.

6. Quantum Computing Example:
Pass: 
- The explanation covers the current state of quantum computing technology and its potential applications, drawing equally from all four sources.
- The response acknowledges the background information provided in the editor content but focuses on current state and applications as requested.
- Clear distinction between the general quantum computing context in editor content and specific details from fetched sources.

Fail: 
- The explanation is overly technical, focuses too much on one aspect (e.g., only on applications or only on current state), or heavily favors one source over the others.
- No indication that the background information from the editor content was considered in framing the response.
- Inability to distinguish between editor content and information from fetched sources.

## Implementation plan

- [x] Update `handleSlashCommand` method
  - Add condition: `if (lastContentBeforeEnter.startsWith('/fetch '))`

- [x] Implement `fetchContent` method with URL validation and error handling
  ```typescript
  async fetchContent(url: string): Promise<string> {
    if (!isValidUrl(url)) {
      throw new Error('Invalid URL');
    }
    try {
      const response = await fetch(`https://r.jina.ai/${encodeURIComponent(url)}`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      return response.text();
    } catch (error) {
      throw new Error(`Failed to fetch content: ${error.message}`);
    }
  }
  ```

- [x] Add error handling
  - Implement try-catch in `handleSlashCommand`
  - Display error messages using existing `showGptErrorToolTipAtBottom`

- [x] Support hash-based content selection
  - Update `fetchContent` to use `x-target-selector` header when hash is present

- [x] Add loading feedback
  - Create methods: `showLoadingIndicator`, `hideLoadingIndicator`

- [x] Update plugin documentation
  - Add explanation and examples for the `/fetch` command in the user guide

- [x] (Optional) Implement multi-URL support
  - Modify `handleSlashCommand` to split input by commas
  - Update `fetchContent` to handle multiple URLs

- [x] Enhance context trimming for fetched content
  ```typescript
  trimFetchedContent(content: string, maxLength: number): string {
    // Implement intelligent trimming logic
    // Return trimmed content
  }
  ```

- [x] Update prompt generation to include fetched content
  ```typescript
  generateGptPromptBasedOnUserPrompt(prompt: string, fetchedContexts: Array<{content: string, url: string}>): string {
    // Combine editor content, user prompt, and fetched contexts
    // Ensure clear demarcation between different contexts
    // Return formatted prompt
  }
  ```

- [x] Adjust `fetchAndProcessGptResponse` to manage tokens across all contexts
  ```typescript
  async fetchAndProcessGptResponse(prompt: string, fetchedContexts: Array<{content: string, url: string}>) {
    const totalTokens = countTokens(prompt) + fetchedContexts.reduce((sum, ctx) => sum + countTokens(ctx.content), 0);
    const availableTokens = this.maxTokens - totalTokens;
    // Adjust API call parameters based on availableTokens
    // Process and insert response
  }
  ```

## Additional considerations

- Ensure the feature integrates smoothly with existing slash command functionality
- Conduct thorough testing, including edge cases with large fetched contents and multiple URLs
- Consider implementing a caching mechanism for frequently fetched URLs to improve performance

## Suggested minimalistic algorithm for dividing contextSize between linked and in-editor corpi

1. Set a target allocation, e.g., 30% for editor content and 70% for fetched content.
2. Calculate initial token counts for both editor and fetched content.
3. If either content type is below its target allocation:
   a. Redistribute the unused tokens to the other content type.
4. If total content exceeds contextSize, proportionally trim both to fit.

This algorithm provides a flexible approach to balancing context between editor and fetched content while respecting the overall context size limit and adapting to the actual content volumes.
