### ISSUE TITLE
Feature proposal: Long-form content support (over 2.000 words)

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/ckeditor5-ai-agent#19]
# Implement Streaming Long-Form Content Generation

## Why are we doing this work

Our AI writing assistant currently has a limitation of generating content up to 2,000 words. This restricts users from creating comprehensive, long-form content in a single operation. By implementing a streaming long-form content generation feature, we'll enable users to create content exceeding 2,000 words from a single prompt, significantly enhancing the tool's capabilities and user productivity.

## Relevant links

- [Design Issue](https://gitlab.com/gitlab-org/gitlab/-/issues/<id>)
- [AI Writing Assistant Technical Documentation]()
- [Long-form Content Generation API Specifications]()
- [Performance Benchmarks for AI-Generated Long-form Content]()

## Requirements

1. Implement a classification system to identify long-form content requests (exceeding 2,000 words).
2. Develop an outline generation process for long-form content requests.
3. Create a section expansion mechanism that maintains context and coherence across the entire piece.
4. Implement a streaming content generation system that produces and sends content to the editor in real-time.
5. Ensure compatibility with various content types (e.g., blog posts, basic pages, product pages).
6. Implement error handling and recovery mechanisms for the streaming process.
7. Develop a user interface for initiating and managing long-form content generation.
8. Implement a mechanism to pause, resume, and cancel long-form content generation.

## Non-functional requirements

- [ ] Performance:
  - Ensure streaming speed averages at least 50 words per minute for 95% of long-form content generations.
  - System should handle multiple concurrent long-form content generation requests without significant degradation in performance.

- [ ] Testing:
  - Conduct cross-browser compatibility tests for the streaming functionality.
  - Perform load testing to ensure stability under concurrent long-form content generation.

## Implementation plan

1. [ ] Update `AiAssist` class constructor
   - Add new properties for long-form content generation (e.g., `maxLongFormTokens`, `outlineGenerationModel`)

2. [ ] Implement `classifyContentRequest` method
   - Use LLM to determine if the request is for long-form content

3. [ ] Create `generateOutline` method
   - For long-form requests, generate a content outline using LLM

4. [ ] Modify `fetchAndProcessGptResponse` method
   - Add logic to handle long-form content generation
   - Implement streaming for long-form content

5. [ ] Update `generateGptPromptBasedOnUserPrompt` method
   - Adjust prompt generation for long-form content requests

6. [ ] Implement `expandOutlineSection` method
   - Generate content for each section of the outline

7. [ ] Modify `handleSlashCommand` method
   - Integrate long-form content generation flow

8. [ ] Update error handling in `fetchAndProcessGptResponse`
   - Add specific error handling for long-form content generation issues

9. [ ] Implement `pauseLongFormGeneration` method
   - Allow pausing of long-form content generation

10. [ ] Implement `resumeLongFormGeneration` method
    - Allow resuming of paused long-form content generation

11. [ ] Update `initializeUIComponents` method
    - Add UI elements for long-form content generation controls

12. [ ] Modify `attachListener` method
    - Add event listeners for long-form content generation controls

13. [ ] Update `validateAssistConfiguration` method
    - Add validation for new long-form content generation settings

### LLM-based Classifier

```typescript
class ContentClassifier {
  private aiModel: AIModel;

  constructor(aiModel: AIModel) {
    this.aiModel = aiModel;
  }

  async classifyPrompt(prompt: string): Promise<boolean> {
    const classificationPrompt = `
      Analyze the following content request and determine if it requires a structured outline approach:
      "${prompt}"
      Respond with only "true" if the request is for long-form content, complex structures, or would benefit from an outline-based approach.
      Respond with only "false" for simple, short requests that don't require extensive structuring.
      Base your decision on the complexity and length of the expected output, not on specific keywords or language.
    `;

    const response = await this.aiModel.generateResponse(classificationPrompt);
    return response.trim().toLowerCase() === 'true';
  }
}
```

### Streaming Content Generator

```typescript
class StreamingContentGenerator {
  private aiModel: AIModel;
  private outlineGenerator: OutlineGenerator;

  constructor(aiModel: AIModel, outlineGenerator: OutlineGenerator) {
    this.aiModel = aiModel;
    this.outlineGenerator = outlineGenerator;
  }

  async *generateContent(prompt: string): AsyncGenerator<string, void, unknown> {
    const outline = await this.outlineGenerator.generateOutline(prompt);
    
    for (const section of outline) {
      const sectionPrompt = `Expand on the following section of "${prompt}": ${section}`;
      const stream = this.aiModel.generateStreamingResponse(sectionPrompt);
      
      for await (const chunk of stream) {
        yield chunk;
      }
    }
  }
}

// Usage in an API endpoint
app.post('/generate-content', async (req, res) => {
  const { prompt } = req.body;
  const classifier = new ContentClassifier(aiModel);
  const generator = new StreamingContentGenerator(aiModel, outlineGenerator);

  const isLongForm = await classifier.classifyPrompt(prompt);

  if (isLongForm) {
    res.writeHead(200, {
      'Content-Type': 'text/plain',
      'Transfer-Encoding': 'chunked'
    });

    for await (const chunk of generator.generateContent(prompt)) {
      res.write(chunk);
    }

    res.end();
  } else {
    // Handle short-form content generation
    const content = await aiModel.generateResponse(prompt);
    res.json({ content });
  }
});
```

## Example Prompts

| Prompt | Long-form (2,000+ words)? |
|--------|---------------------------|
| "Write a comprehensive guide on how to start a successful e-commerce business" | Yes |
| "Create a 3000-word product description for our new smartphone, including all features and specs" | Yes |
| "Explain the process of machine learning from beginner to advanced level" | Yes |
| "Write a 2500-word history of our company from its founding to present day" | Yes |
| "Provide an in-depth analysis of renewable energy sources and their potential impact on climate change" | Yes |
| "Create a complete guide for attendees of our annual tech conference, covering all events and speakers" | Yes |
| "Write a 4000-word investigative report on the effects of urban development on local ecosystems" | Yes |
| "Generate a comprehensive FAQ for our cloud computing services" | Yes |
| "Write a detailed job posting for a senior software engineer, including company culture and benefits" | Yes |
| "Produce a 2000-word article on the latest trends in biotechnology and their potential applications" | Yes |
| "Write a product description for our new coffee blend" | No |
| "Create a 150-word editor's note for this month's blog post" | No |
| "Generate a brief company overview for our homepage" | No |
| "Summarize next week's community event in about 250 words" | No |
| "Write a news update about our recent partnership" | No |
| "Create a teaser for our upcoming webinar series" | No |
| "Write a 200-word introduction for our new CEO" | No |
| "Generate a product spotlight for this week's newsletter" | No |
| "Summarize the key points from our annual report" | No |
| "Write a job summary for a marketing intern position in about 150 words" | No |

**Comment by jjroelofs** [comment]
shelved
