### ISSUE TITLE
Enhance AI Prompt Settings with Web Content Related Context

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/ckeditor5-ai-agent#25]
## Why are we doing this work

We are enhancing our AI-assisted content creation tool to provide more tailored and context-aware content generation. By adding new optional string prompt settings and refactoring existing settings, we aim to improve the quality and relevance of AI-generated content. This will allow content creators to better leverage site-wide, content-type specific, localization settings, and content-specific details, resulting in more accurate and contextually appropriate content.

## Requirements

1. Add new optional string prompt settings:
   - `sitewideSettings`: toneOfVoice, brandingGuidelines, siteDescription, targetAudience
   - `contentTypeSettings`: type, toneOfVoice, targetAudience
   - `userSettings`: toneOfVoice
   - `localizations`: targetLocale, culturalConsiderations
   - `contentItemSettings`: contentTitle, contentTags, contentField

2. Refactor existing prompt settings to be optional strings:
   - Change `outputFormat` from Array<string> to optional string
   - Change `contextData` from Array<string> to optional string
   - Change `filters` from Array<string> to optional string

3. Update the `PromptHelper` class to utilize these new and refactored settings

4. Modify the `getSystemPrompt` method to incorporate the new settings into the AI prompt

5. Modify existing prompt components to remove instructions that affect style and tone (e.g. remove `Use a relaxed, formal or informal tone based on the summary of context with lots of personal touches.` and `Add in personal anecdotes or emotional reactions to make it sound like a genuine conversation.` and ` Avoid overly polished language or structured sentences, aim for a natural and solely human-like tone.` etc.

6. Update any relevant documentation to reflect these changes

## Non-functional requirements

- [ ] Documentation: Update the README.md and any relevant API documentation to reflect the new prompt settings and their usage
- [ ] Testing: Add unit tests for the new prompt settings and refactored code
- [ ] Performance: Ensure that the addition of new prompt settings does not significantly impact the response time of the AI content generation

## Implementation plan

1. [ ] Update `src/augmentation.ts`
   - [ ] Add new prompt settings to the `EditorConfig` interface
   - [ ] Refactor existing settings (outputFormat, contextData, filters) to be optional strings

   ```typescript
   interface EditorConfig {
     aiAssist?: {
       // ... existing settings ...
       promptSettings?: {
         outputFormat?: string;
         contextData?: string;
         filters?: string;
         sitewideSettings?: {
           toneOfVoice?: string;
           brandingGuidelines?: string;
           siteDescription?: string;
           targetAudience?: string;
         };
         contentTypeSettings?: {
           type?: string;
           toneOfVoice?: string;
           targetAudience?: string;
         };
         userSettings?: {
           toneOfVoice?: string;
         };
         localizations?: {
           targetLocale?: string;
           culturalConsiderations?: string;
         };
         contentItemSettings?: {
           contentTitle?: string;
           contentTags?: string;
           contentField?: string;
         };
       };
       // ... other settings ...
     };
   }
   ```

2. [ ] Update `src/util/prompt.ts`
   - [ ] Modify the `PromptHelper` class to include new private properties for the new settings
   - [ ] Update the constructor to initialize these new properties
   - [ ] Refactor existing properties (responseOutputFormat, responseContextData, responseFilters) to be strings

   ```typescript
   export class PromptHelper {
     private responseOutputFormat: string;
     private responseContextData: string;
     private responseFilters: string;
     private sitewideSettings: Record<string, string>;
     private contentTypeSettings: Record<string, string>;
     private userSettings: Record<string, string>;
     private localizations: Record<string, string>;
     private contentItemSettings: Record<string, string>;

     constructor(editor: Editor) {
       const config = editor.config.get('aiAssist')!;
       // ... existing initialization ...
       this.responseOutputFormat = config.promptSettings?.outputFormat ?? '';
       this.responseContextData = config.promptSettings?.contextData ?? '';
       this.responseFilters = config.promptSettings?.filters ?? '';
       this.sitewideSettings = config.promptSettings?.sitewideSettings ?? {};
       this.contentTypeSettings = config.promptSettings?.contentTypeSettings ?? {};
       this.userSettings = config.promptSettings?.userSettings ?? {};
       this.localizations = config.promptSettings?.localizations ?? {};
       this.contentItemSettings = config.promptSettings?.contentItemSettings ?? {};
     }

     // ... other methods ...
   }
   ```

3. [ ] Modify the `getSystemPrompt` method in `src/util/prompt.ts`
   - [ ] Add logic to incorporate new settings into the AI prompt
   - [ ] Update handling of refactored settings (now optional strings)

   ```typescript
   public getSystemPrompt(): string {
     const corpus: Array<string> = [];
     // ... existing corpus pushes ...

     if (this.responseOutputFormat) {
       corpus.push(`Output Format: ${this.responseOutputFormat}`);
     }
     if (this.responseContextData) {
       corpus.push(`Context Data: ${this.responseContextData}`);
     }
     if (this.responseFilters) {
       corpus.push(`Filters: ${this.responseFilters}`);
     }

     this.addSettingsToCorpus(corpus, 'Sitewide settings', this.sitewideSettings);
     this.addSettingsToCorpus(corpus, 'Content type settings', this.contentTypeSettings);
     this.addSettingsToCorpus(corpus, 'User settings', this.userSettings);
     this.addSettingsToCorpus(corpus, 'Localization settings', this.localizations);
     this.addSettingsToCorpus(corpus, 'Content item specific details', this.contentItemSettings);

     // ... rest of the method ...
   }

   private addSettingsToCorpus(corpus: string[], title: string, settings: Record<string, string>) {
     const settingsEntries = Object.entries(settings).filter(([, value]) => value);
     if (settingsEntries.length > 0) {
       corpus.push(`Consider the following ${title}:`);
       settingsEntries.forEach(([key, value]) => {
         corpus.push(`- ${key}: ${value}`);
       });
     }
   }
   ```

4. [ ] Update `src/aiassist.ts`
   - [ ] Modify the default configuration to include the new prompt settings as empty strings

6. [ ] Update tests
   - [ ] Add new unit tests for the added functionality in `test/prompt.js`
   - [ ] Modify existing tests to account for refactored settings

   ```javascript
   describe('PromptHelper', () => {
     it('should include all provided prompt settings in the system prompt', () => {
       // ... test setup with all settings provided ...
       const systemPrompt = promptHelper.getSystemPrompt();
       expect(systemPrompt).to.include('Sitewide settings:');
       expect(systemPrompt).to.include('Content type settings:');
       expect(systemPrompt).to.include('User settings:');
       expect(systemPrompt).to.include('Localization settings:');
       expect(systemPrompt).to.include('Content item specific details:');
     });

     it('should not include empty settings in the system prompt', () => {
       // ... test setup with some empty settings ...
       const systemPrompt = promptHelper.getSystemPrompt();
       expect(systemPrompt).to.not.include('User settings:');
     });

     // ... other tests ...
   });
   ```

7. [ ] Update documentation
   - [ ] Update README.md with information about the new optional string prompt settings
   - [ ] Update any API documentation to reflect the changes

8. [ ] Perform manual testing to ensure the new settings are correctly incorporated into the AI prompts

9. [ ] Create a pull request with the changes and request review from the team
