### ISSUE TITLE
Implement ESLint max-lines Rule and Refactor Codebase

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/ckeditor5-ai-agent#26]
## Why are we doing this work

We are implementing the ESLint max-lines rule to improve code readability and maintainability in our project. By limiting the number of lines in each file, we encourage better code organization, modularization, and adherence to the Single Responsibility Principle. This will make our codebase easier to understand, test, and maintain in the long run.

We will also improve the naming conventions in our styles to follow a consistent BEM methodology, as well as update our CSS to use shared variables for better maintainability. This includes introducing CKEditor’s theme variables where appropriate. We want to use the .ce- class prefix for all UI CSS. Please look at CSS in other plugins for inspiration.

## Relevant links

- [ESLint max-lines rule documentation](https://eslint.org/docs/rules/max-lines)
- [Clean Code: Chapter 3 - Functions](https://github.com/ryanmcdermott/clean-code-javascript#functions)
- [CKEditor 5 Theme Customization Documentation](http://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/ui/theme-customization.html#customization-with-css-variables)

## Requirements

1. Add the max-lines rule to our ESLint configuration with default settings (300 lines per file).
2. Run ESLint across the entire project to identify files exceeding the limit.
3. Refactor identified files to comply with the new rule:
   - Split large files into smaller, more focused modules.
   - Extract utility functions or classes where appropriate.
   - Ensure that the refactoring doesn't break existing functionality.
   - Update class naming in styles to follow BEM conventions and CKEditor’s naming conventions.
   - Replace hard-coded style values with appropriate CKEditor CSS variables for consistent theming.
4. Update any necessary import statements in other files affected by the refactoring.
5. Ensure all tests pass after refactoring.
6. Update documentation if file structures, exports, or styling conventions have changed significantly.

## Non-functional requirements

- [ ] Documentation: Update contributor guidelines to mention the max-lines rule and provide guidance on file organization and the new naming conventions.
- [ ] Testing: Ensure all existing tests pass after refactoring. Add new tests for any new modules created during the process.
- [ ] Performance: Monitor build times and application performance to ensure the refactoring doesn't negatively impact either.

## Implementation plan

1. [ ] Update ESLint configuration
   - [ ] Add the max-lines rule to .eslintrc.js:
     ```javascript
     module.exports = {
       // ... existing config ...
       rules: {
         // ... other rules ...
         'max-lines': ['error', 300]
       }
     };
     ```

2. [ ] Identify non-compliant files
   - [ ] Run ESLint on the entire project and save the output:
     ```
     npx eslint . --format json > eslint-report.json
     ```
   - [ ] Parse the JSON output to identify files exceeding the 300-line limit.

3. [ ] Refactor identified files
   - [ ] For each file exceeding the limit:
     - [ ] Analyze the file structure and identify logical separation points.
     - [ ] Extract functions or classes into separate files where appropriate.
     - [ ] Update import/export statements in the original and new files.
     - [ ] Ensure the refactored code maintains the original functionality.
   - [ ] Update class names in stylesheets to follow BEM conventions (e.g., `ck-gpt-loader--visible` instead of `.show-gpt-loader`).
   - [ ] Replace hard-coded CSS values with CKEditor’s variables (e.g., `--ck-color-input-background` for background colors).

4. [ ] Update affected imports
   - [ ] Search for imports referencing the refactored files.
   - [ ] Update import statements in other parts of the codebase to reflect the new file structure.

5. [ ] Run and update tests
   - [ ] Run the existing test suite to ensure no functionality was broken:
     ```
     npm run test
     ```
   - [ ] Update any tests that were affected by the file restructuring.
   - [ ] Add new tests for any new modules created during refactoring.

6. [ ] Update documentation
   - [ ] Review and update any documentation that references file structures, exports, or styling conventions that have changed.
   - [ ] Update the contributor guidelines to include information about the max-lines rule and the updated BEM class naming convention.

7. [ ] Final verification
   - [ ] Run ESLint again to ensure all files now comply with the max-lines rule:
     ```
     npx eslint .
     ```
   - [ ] Run the full test suite one more time to ensure everything is working correctly.

8. [ ] Create a pull request with the changes and request review from the team.
