### ISSUE TITLE
 Enable Slash Command in Any Text Context with Toolbar Button

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/ckeditor5-ai-agent#8]
### Summary
The current slash command interface only works on newlines and does not function inside lists, tables, or other structured content. The goal of this issue is to enhance the plugin so that the slash command can be used in any text context. This includes, but is not limited to:

1. At the end of a paragraph (example command: finish this paragraph)
2. Inside a list (example command: next item)
3. Inside a table cell (example command: /fill cell)

By introducing a toolbar button labeled "AI Assistant," we want to make it easier for users to trigger the slash command functionality in all text contexts.

### Why are we doing this work
This work focuses on expanding the utility of the slash command interface so that users can interact with it inside various text structures (lists, tables, etc.) by simply clicking a toolbar button. This enhancement aims to improve user productivity and flexibility, particularly in more complex documents. 

The dropdown menu for commands is out of scope for this issue and will be handled in [the next issue](https://github.com/dxpr/ckeditor5-ai-assist/issues/9).

![image](https://github.com/user-attachments/assets/5912cbb8-860f-46e9-a1da-d495698aee28)

![flashing-slash](https://github.com/user-attachments/assets/d3bc6b9c-8512-4cb1-96bd-02a0347571b9)

### Relevant links
- [CodePen Slash Animation Demo](https://codepen.io/Jurriaan-Roelofs/pen/OJeQYRp)

SVG icoin:
```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M4.00815 5.01816H19.3851V10.9145H21.1594V3.2439H2.23389V22.1694H12.3955V20.3951H4.00815V5.01816Z" fill="#222330"/>
<path d="M15.1908 20.046L20.9028 12.7065L22.9998 14.3385L17.2878 21.678L15.0341 22.755C14.8582 22.8391 14.6619 22.6862 14.7002 22.4951L15.1908 20.046Z" fill="#222330"/>
<path d="M16.1211 8.43794V15.7494H14.5753V8.43794H16.1211Z" fill="#222330"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M8.31458 15.7495H6.65807L9.18211 8.43804H11.1742L13.6947 15.7495H12.0382L11.4968 14.0823H8.85696L8.31458 15.7495ZM10.2067 10.1088L11.1051 12.8756H9.24951L10.1496 10.1088H10.2067Z" fill="#222330"/>
</svg>
```

### Requirements
- Modify the plugin to allow the slash command to work in any text context (paragraphs, lists, tables, etc.).
- Add a new optional "AI Assistant" button to the toolbar.
  - When clicked, the button should insert a slash (`/`) into the active text area.
  - The slash should appear with a brief animation that includes a subtle black glow.
  - After the animation, the slash should blend seamlessly into the normal text.
- Use all the animation code from the linked CodePen, including the accessibility feature for WCAG AA compliance.
- Use the custom SVG icon from the CodePen.
- Command prompt functionality should work with or without the optional toolbar button, allowing users to exclude the toolbar button while still having access to the command prompt UI when the plugin is included.
- Add comprehensive test coverage for the button's functionality, based on the same test system that is included in the example code for the button. (`yarn run test`) https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/testing-environment.html

### Non-functional requirements
- [ ] Documentation: Update relevant user guides to include the new AI Assistant button and expanded functionality for slash commands.
- [ ] Feature flag: Introduce a feature flag to enable or disable the AI Assistant button for testing and rollout purposes.
- [ ] Performance: Ensure that the addition of the button and animation does not degrade editor performance.
- [ ] Testing: Implement automated tests to verify that the slash command works in all text contexts, the button functions correctly, and the animation appears as expected.

### Implementation plan @todo
Note: This repo already contains a demo button that can be adapted to print the slash instead of the default text:

https://github.com/dxpr/ckeditor5-ai-assist/blob/ad082f613b421600fa2cc018141abda8eae280e5/src/aiassist.ts#L17-L38

---

Let me know if you’d like any further adjustments!
